#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#define MAX 1000
#define seed 1

unsigned int getExpectedRandomOutput() 
{
    int r[MAX];
    int i;

    r[0] = seed;
    for (i = 1; i < 31; i++)
    {
        r[i] = (16807LL * r[i - 1]) % 2147483647;
        if (r[i] < 0)
        {
            r[i] += 2147483647;
        }
    }
    for (i = 31; i < 34; i++)
    {
        r[i] = r[i - 31];
    }
    for (i = 34; i < 344; i++)
    {
        r[i] = r[i - 31] + r[i - 3];
    }
    i = 344;
    r[i] = r[i - 31] + r[i - 3];
    return ((unsigned int)r[i]) >> 1;
}

bool isStdRandom(unsigned int num)
{
    unsigned int expected = getExpectedRandomOutput();
    return (num == expected);
}

int main(void)
{
    unsigned int randomVal = (unsigned int)random();
    printf("Random value: %u, is generated by random(): %d\n", randomVal, isStdRandom(randomVal));

    unsigned int cryptoSecureRand = arc4random();
    printf("Random value: %u, is generated by random(): %d\n", cryptoSecureRand, isStdRandom(cryptoSecureRand));
}